### ISSUE TITLE
Buff/Debuff tracking on nameplates stop working when this addon is enabled

### ISSUE THREAD

**Issue by Senkaiwow** [Zidras/ElvUI_ProjectZidras#10]
The addon works fine, but like the title says, as soon as I enable this addon with the 3.3.5 HD client, the ElvUI Nameplate Buffs and Debuffs stop working. It does not matter if the "HD-nameplates" setting in the addon is enabled or not
![mzj226d](https://user-images.githubusercontent.com/95051198/143494544-741e2a58-ebcd-4940-b69b-b06116f43968.png)
![ao1qmEF](https://user-images.githubusercontent.com/95051198/143494546-7caa43ff-2d6f-4eb8-a6d9-86027f29a9e2.png)

.

**Comment by Zidras** [comment]
What does it mean, stops working? What should be the expected look?

**Comment by Senkaiwow** [comment]
Like at the bottom screenshot, the debuffs should be above the each nameplate. I just tried another addon that does the same: "PlateBuffs", but this addon also stops working when I enable ElvUI_ProjectZidras

**Comment by Zidras** [comment]
What I mean is, how does it appear to you without the plugin? A screenshot will help

**Comment by Senkaiwow** [comment]
In the bottom screenshot the plugin is disabled, here's another one I guess. not sure if this is what you mean though
![lU8muQg](https://user-images.githubusercontent.com/95051198/143495590-874b5d74-3656-4366-ae71-8e3827e6b153.png)

**Comment by Zidras** [comment]
Yes that's what I needed to see thanks. I honestly don't see difference on the buff anchoring between your screenshot with and without pz

**Comment by Zidras** [comment]
Nvm, just realized your first two ss were with and without the option.

**Comment by Zidras** [comment]
Enable lua errors, and only have elvui, options and PZ enabled please. Let me know the results

**Comment by Senkaiwow** [comment]
Maybe I should've wrote it in the screenshot to make my point more abvious, sorry :D

**Comment by Senkaiwow** [comment]
Alright. Right after logging in after disabling the addons, I get this LUA error: 


Message: ...lvUI_ProjectZidras\Modules\Nameplates\Nameplates.lua:71: attempt to call method 'GetUnitTypeFromUnit' (a nil value)
Time: 11/25/21 21:12:51
Count: 1
Stack: ...lvUI_ProjectZidras\Modules\Nameplates\Nameplates.lua:71: in function `CacheGroupUnits'
...rface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:1169: in function `Initialize'
...rface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:1187: in function <...rface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:1186>
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:155: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\Core\Core.lua:1081: in function `CallLoadedModule'
Interface\AddOns\ElvUI\Core\Core.lua:1106: in function `InitializeModules'
Interface\AddOns\ElvUI\Core\Core.lua:1266: in function <Interface\AddOns\ElvUI\Core\Core.lua:1243>
[C]: in function `Initialize'
Interface\AddOns\ElvUI\Init.lua:210: in function <Interface\AddOns\ElvUI\Init.lua:209>

Locals: self = <table> {
 GetUnitInfo = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:283
 Configure_Highlight = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Elements\Highlight.lua:22
 ForEachVisiblePlate = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:480
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:166
 SecureHook = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:336
 CutawayHealthColorChangeCallback = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Elements\CutawayHealth.lua:46
 OnCreated = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:544
 StyleFilterRemoveCustomCheck = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\StyleFilter.lua:830
 SetAura = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Elements\Auras.lua:112
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:968
 UNIT_COMBO_POINTS = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:962
 ConfigureAll = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:460
 CheckBGHealers = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:62
 IsEnabled = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:482
 LibAuraInfo_AURA_REFRESH = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Elements\Auras.lua:60
 RAID_TARGET_UPDATE = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:1010
 SetPlateFrameLevel = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:94
 RegisterMessage = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 ResetSettings = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:918
 Construct_CPoints = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Elements\ComboPoints.lua:101
 hooks = <table> {
 }
 db = <table> {
 }
 TogleTestFrame = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:1080
 ENEMY_NPC = <table> {
 }
 Hook = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:274
 UPDATE_MOUSEOVER_UNIT = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:947
 UpdateTime = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Elements\Auras.lua:76
 GetPlateFrameLevel = <function> defined @Interface\AddOns\ElvUI\Modules\Nameplates\Nameplates.lua:86
 Update_CooldownOptions = <function> defined @Interface

**Comment by Zidras** [comment]
Your elvui is outdated. Update to latest Master version.

**Comment by madlemonyt** [comment]
Thank you, that fixed it for me. I had ElvUI 6.08 from my archives :D 
Newest version is 6.09!
