### ISSUE TITLE
[Feature Request] Timeframe Healing Prediction - Prediction Inclusion Limit by Time

### ISSUE THREAD

**Issue by Ithiloneth** [Zidras/ElvUI_ProjectZidras#11]
Healbot includes a setting which changes what to include in Healing Prediction. It is a very important feature.
For example, when in group with a Restoration Druid all _practically all bars_ are showing as being expected to be fully healed, all the time. This means you both can't tell if some other healer is hardcasting a direct heal on that target, it also means you don't know if that target is about to die since not enough healing is inbound.

Here is how Healbot's setting works:
If a heal is being cast on a target, and the cast time is >2 seconds, a setting of "Timeframe 2 seconds" means the heal would not be displayed.
When there is <=2 seconds remaining on the cast the heal is included then displayed prediction.

A separate setting is available for Healing Over Time (HoT) spells which has the same function.

![image](https://user-images.githubusercontent.com/20944949/148706236-5b326588-a8df-475b-84fa-03e1875158a4.png)

**Comment by Zidras** [comment]
I had to disable the lookahead during development because it was breaking the statusbar after the first callback:
https://github.com/Zidras/ElvUI_ProjectZidras/blob/aecb634fd4c3203a54224cb80b0023bc918b331a/ElvUI_ProjectZidras/Libraries/oUF_Plugins/HealthPrediction.lua#L116-L117

It is a good suggestion for me to revisit when I can and attempt a fix.

**Comment by Ithiloneth** [comment]
Thank you Zidras - please do attempt a re-visit!

It is about the only feature I can think of that ElvUI lacks when compared to Healbot which is drastically important to healers (of the type who like me make split-second decisions to minimize overhealing).

**Comment by Ithiloneth** [comment]
Thank you for giving this some attention Zidras.

I fail to see how the issue is resolved however? Am I missing something in the UI where HoTs and Direct Heals can be set to have specific time frame limits?

Made a comment on the commit itself!
https://github.com/Zidras/ElvUI_ProjectZidras/commit/cfee0c81a2a93031e0a9472f07100f097d9191a0

**Comment by Zidras** [comment]
Check discord. Has video

**Comment by Zidras** [comment]
Also there is no separation between heal type, since elvui heal prediction element would require rewrite to accommodate all heal types. Time-frame applies to all heals

**Comment by Ithiloneth** [comment]
Thank you Zidras.

Good to see this implemented - it be a big help, even if all healing is on the same slider.
Very happy about this update!

For those looking for the settings, you find them here:
![image](https://user-images.githubusercontent.com/20944949/188139467-ae98c126-3eca-4579-91ab-83da22f9a294.png)
