### ISSUE TITLE
Testing zidra in HD client, bug?

### ISSUE THREAD

**Issue by Milor123** [Zidras/ElvUI_ProjectZidras#5]
Hi dear friend, i am trying use your plugin in my wow 3.3.5 hd client of warmane
![imagen](https://user-images.githubusercontent.com/14153649/139598614-7915cd27-4491-4065-aaa5-09d75f48ac56.png)

[Log Error file Here](https://pastebin.com/tEBc8uLy)

I would like how can solve it?

Thank u very much for you work !! is great!

**Comment by Zidras** [comment]
Hello, can you test with only ElvUI and plugin?

**Comment by Milor123** [comment]
> Hello, can you test with only ElvUI and plugin?

Its the Swatter addon, when disable it dont show the error.
But reading about of Swatter is a debugging tool 
> "Rather than simply popping up the big red box on your screen when addons break or do bad things, Swatter pops up a nice dialog box that includes the error, how many errors have occurred previously during the current session, the number of times the specific error has occurred this session, a stack trace, and a complete list of loaded AddOns."

**Comment by Zidras** [comment]
Attach your version of Swatter here and I'll try to reproduce on my end

**Comment by Zidras** [comment]
I can't reproduce with the addon you sent me. Most likely the code isn't running at the right time for you due to other addons :(

**Comment by Zidras** [comment]
Fixed with https://github.com/Zidras/ElvUI_ProjectZidras/commit/11b8b7792afcc75d50328498b830f72b6f12cf8f

**Comment by Milor123** [comment]
Thank you very much for u great addon !!! @Zidras
